import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/global.scss'
import { Header } from '@/widgets/Header'

const inter = Inter({
  variable: '--font-family',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
