name: build-and-deploy

on:
  push:
    branches:
      - main   # или другая ветка, с которой хочешь деплоить

env:
  REGISTRY: urbanspace.azurecr.io        # имя ACR
  IMAGE_NAME: next-frontend            # имя образа
  RESOURCE_GROUP: urban_space            # имя resource group
  CONTAINERAPP_NAME: urban-space-frontend # имя Container App

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login $REGISTRY \
            -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build & Push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build --build-arg NEXT_PUBLIC_API_BASE_URL="${{ secrets.NEXT_PUBLIC_API_BASE_URL }}" \
          -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name $CONTAINERAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $REGISTRY/$IMAGE_NAME:${{ env.IMAGE_TAG }}